-- Roles
CREATE TABLE IF NOT EXISTS `Roles` (
    `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Name` VARCHAR(255) UNIQUE NOT NULL,
    `Description` TEXT,
    `Delete` BOOLEAN DEFAULT FALSE,
    `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Modules
CREATE TABLE IF NOT EXISTS `Modules` (
    `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Name` VARCHAR(255) UNIQUE NOT NULL,
    `Description` TEXT,
    `Enabled` BOOLEAN DEFAULT FALSE,
    `Deleted` BOOLEAN DEFAULT FALSE,
    `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- PermissionMatrix
CREATE TABLE IF NOT EXISTS `Permissions` (
    `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Read` BOOLEAN DEFAULT FALSE,
    `Write` BOOLEAN DEFAULT FALSE,
    `ModuleID` INT UNSIGNED NOT NULL,
    `RoleID` INT UNSIGNED NOT NULL,
    `Deleted` BOOLEAN DEFAULT FALSE,
    `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`ModuleID`) REFERENCES `Modules` (`ID`),
    FOREIGN KEY (`RoleID`) REFERENCES `Roles` (`ID`)
);

-- Users
CREATE TABLE IF NOT EXISTS `Users` (
    `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Username` VARCHAR(255) UNIQUE NOT NULL,
    `Password` VARCHAR(255) NOT NULL,
    `RoleID` INT UNSIGNED NOT NULL,
    `Deleted` BOOLEAN DEFAULT FALSE,
    `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`RoleID`) REFERENCES `Roles` (`ID`)
);

-- TransactionTypes
CREATE TABLE IF NOT EXISTS `TransactionTypes` (
    `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Name` VARCHAR(255) UNIQUE NOT NULL,
    `Description` TEXT,
    `Deleted` BOOLEAN DEFAULT FALSE,
    `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- TransactionGroups
CREATE TABLE IF NOT EXISTS `TransactionGroups` (
    `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Name` VARCHAR(255) UNIQUE NOT NULL,
    `Description` TEXT,
    `Deleted` BOOLEAN DEFAULT FALSE,
    `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Transactions
CREATE TABLE IF NOT EXISTS `Transactions` (
    `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Date` DATE NOT NULL DEFAULT CURRENT_DATE,
    `Annotation` TEXT,
    `TransactionTypeID` INT UNSIGNED NOT NULL,
    `TransactionGroupID` INT UNSIGNED NOT NULL,
    `UserID` INT UNSIGNED NOT NULL,
    `Deleted` BOOLEAN DEFAULT FALSE,
    `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`TransactionTypeID`) REFERENCES `TransactionTypes` (`ID`),
    FOREIGN KEY (`TransactionGroupID`) REFERENCES `TransactionGroups` (`ID`),
    FOREIGN KEY (`UserID`) REFERENCES `Users` (`ID`)
);